server:
  port: 8200
micros:
  application:
    name: data
  datasource:
    general:
      master:
        url: 'jdbc:mysql://${micros.datasource.server}/ms_data?characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true&useSSL=false'
      slaves:
        database: ${micros.datasource.server}/ms_data_read
        username: micros_all_read
    defaults:
      url-template: 'jdbc:mysql://${database}?characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false'
      username: micros_all
      password: p@ssword
    multi-tenants:
      1138238647:
        master:
          database: localhost/ms_data_example
        slaves:
          database: localhost/ms_data_example_read
          username: micros_all_read
spring:
  cloud:
    stream:
      bindings:
        createAccount:
          destination: createAccounts
          group: data
        updateAccount:
          destination: updateAccounts
          group: data
        deleteAccount:
          destination: deleteAccounts
          group: data