server:
  port: 8000
spring:
  cloud:
    gateway:
      routes:
      - id: service-auth
        uri: lb://service-auth
        predicates:
          - Path=/auth-api/**
        filters:
          - StripPrefix=1
      - id: service-data
        uri: lb://service-data
        predicates:
        - Path=/data-api/**
        filters:
        - StripPrefix=1
feign:
  client:
    config:
      default:
        connect-timeout: 1000
        read-timeout: 3000