server:
  port: 8000
spring:
  cloud:
    gateway:
      routes:
        - id: service-auth
          uri: lb://service-auth
          predicates:
            - Path=/auth-api/**
          filters:
            - StripPrefix=1
        - id: service-data
          uri: lb://service-data
          predicates:
            - Path=/data-api/**
          filters:
            - StripPrefix=1
        - id: service-form
          uri: lb://service-form
          predicates:
            - Path=/form-api/**
          filters:
            - StripPrefix=1
            - name: Retry
              args:
                retries: 2
                series:
                  - SERVER_ERROR
                methods:
                  - GET
                  - PUT
                  - DELETE
                exceptions:
                  - java.lang.Exception
feign:
  client:
    config:
      default:
        connect-timeout: 1000
        read-timeout: 3000