server:
  port: 8100
micros:
  application:
    name: auth
spring:
  cloud:
    stream:
      bindings:
        createAccount:
          destination: createAccounts
        updateAccount:
          destination: updateAccounts
        deleteAccount:
          destination: deleteAccounts