server:
  port: 8200
micros:
  application:
    name: data
spring:
  cloud:
    stream:
      bindings:
        createAccount:
          destination: createAccounts
          group: data
        updateAccount:
          destination: updateAccounts
          group: data
        deleteAccount:
          destination: deleteAccounts
          group: data